version: '3.9'

services:
  upload_gridfs_test:
    container_name: upload_gridfs_test
    build:
      context: .
      dockerfile: test/Dockerfile
    volumes:
      - ./:/app

networks:
  upload_gridfs:
    external: true
    name: upload_gridfs